### ISSUE TITLE
dev: Update to the latest starknet-rs version in `l3`

### ISSUE THREAD

**Issue by akhercha** [keep-starknet-strange/zaun#23]
We want to update to the latest `starknet-rs` version in our `l3` crates and replace our different `FieldElement` (from starknet_ff / starknet_core ...) usages by the new Felt type.

This will allow us to use the `AppchainCoreContract` in [madara-orchestrator](https://github.com/karnotxyz/madara-orchestrator).

**Comment by od-hunter** [comment]
Hello sir @akhercha , can I take this up now? I’m available to work. Sorry I just responded didn’t see this earlier.

**Comment by akhercha** [comment]
Hey @od-hunter - I'm sorry but we already have someone from the Madara squad that will handle this task. Thanks for your help anyway 🙏

**Comment by od-hunter** [comment]
> Hey @od-hunter - I'm sorry but we already have someone from the Madara squad that will handle this task. Thanks for your help anyway 🙏

Ok ser, please I’m open to orher issues. Sorry for the delay in replying once more.
